import { mat4, vec3, quat } from 'gl-matrix';


// Camera code generated by Claude with some manual cleanup.
export class Camera {
    position = vec3.fromValues(0, 0, 6371 + 800);
    
    // Orientation as a quaternion, relative to planet-up frame
    // Identity = looking along the planet surface tangent
    private orientation = quat.identity(quat.create());

    fov = Math.PI / 3;
    aspect = 16 / 9;
    near = 10.0;
    far = 1000000.0;

    readonly viewMatrix = mat4.create();
    readonly projMatrix = mat4.create();
    readonly viewProjectionMatrix = mat4.create();
    readonly invViewProjectionMatrix = mat4.create();
    readonly forward = vec3.create();
    readonly right = vec3.create();
    readonly up = vec3.create();

    constructor(position: vec3) {
        vec3.copy(this.position, position);
        this.update();
    }

    /**
     * Rotate around the camera's local right axis (tilt up/down).
     * Positive = look up (toward zenith), negative = look down (toward nadir).
     */
    rotatePitch(radians: number) {
        const pitchQuat = quat.setAxisAngle(
            quat.create(), 
            this.right, 
            radians
        );
        quat.multiply(this.orientation, pitchQuat, this.orientation);
        quat.normalize(this.orientation, this.orientation);
    }

    /**
     * Rotate around the planet-up axis (look left/right).
     * This is yaw relative to the planet surface.
     */
    rotateYaw(radians: number) {
        const planetUp = vec3.normalize(vec3.create(), this.position);
        const yawQuat = quat.setAxisAngle(quat.create(), planetUp, radians);
        quat.multiply(this.orientation, yawQuat, this.orientation);
        quat.normalize(this.orientation, this.orientation);
    }

    /**
     * Rotate around the camera's local forward axis (tilt sideways).
     */
    rotateRoll(radians: number) {
        const rollQuat = quat.setAxisAngle(
            quat.create(), 
            this.forward, 
            radians
        );
        quat.multiply(this.orientation, rollQuat, this.orientation);
        quat.normalize(this.orientation, this.orientation);
    }

    update() {
        // Planet up = direction away from planet center
        const planetUp = vec3.normalize(vec3.create(), this.position);
        
        // Apply orientation quaternion to get camera basis vectors
        // Start with a reference frame aligned to planet up
        // Reference forward: some tangent vector to planet surface
        // We pick a consistent reference using cross products
        
        // Find a stable reference tangent that doesn't flip near poles
        let refTangent = vec3.fromValues(0, 0, 1);
        if (Math.abs(vec3.dot(refTangent, planetUp)) > 0.99) {
            refTangent = vec3.fromValues(1, 0, 0); // fallback near poles
        }
        
        // Build reference frame: forward is tangent to surface
        const refForward = vec3.normalize(
            vec3.create(),
            vec3.cross(vec3.create(), refTangent, planetUp)
        );
        const refRight = vec3.normalize(
            vec3.create(),
            vec3.cross(vec3.create(), planetUp, refForward)  
        );

        // Apply orientation quaternion to reference frame
        vec3.transformQuat(this.forward, refForward, this.orientation);
        vec3.transformQuat(this.right, refRight, this.orientation);
        vec3.transformQuat(this.up, planetUp, this.orientation);

        // Normalize to clean up float drift
        vec3.normalize(this.forward, this.forward);
        vec3.normalize(this.right, this.right);
        vec3.normalize(this.up, this.up);

        // Build view matrix from basis vectors
        const target = vec3.add(vec3.create(), this.position, this.forward);
        mat4.lookAt(this.viewMatrix, this.position, target, this.up);

        // Projection
        mat4.perspective(this.projMatrix, this.fov, this.aspect, this.near, this.far);

        // Combined
        mat4.multiply(this.viewProjectionMatrix, this.projMatrix, this.viewMatrix);
        mat4.invert(this.invViewProjectionMatrix, this.viewProjectionMatrix);
    }

    setAspect(aspect: number) {
        this.aspect = aspect;
        this.update();
    }

    resetOrientation() {
        // Reset to identity — camera looks along reference tangent, up = planet up
        quat.identity(this.orientation);
        this.update();
    }
}